# NumPy

###### **Indice**
* [NumPy](#numpy)
  * [Array](#array)
    * [Slicing](#slicing)
  * [Tipos de datos](#tipos-de-datos)
    * [`.dtype`](#.dtype)
    * [`.astype`](#.astype)
  * [Dimensiones](#dimensiones)
    * [`.ndim`](#.ndim)
    * [`expand_dims()`](#expand_dims)
    * [`squeeze`](#squeeze)

Si queremos hacer uso de la librería es necesario importarla, la forma mas común de hacerlo es la siguiente:

In [29]:
import numpy as np

## Array
El array es el principal objeto de la librería. Representa datos de manera estructurada y se puede acceder a ellos a través del indexado, a un dato específico o un grupo de muchos datos específicos.

In [30]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

Convertimos nuestra lista en un array

In [31]:
arr = np.array(lista)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Una matriz son varios Vectores o listas agrupadas una encima de la otra

In [32]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

El indexado nos permite acceder a los elementos de los array y matrices
Los elementos se empiezan a contar desde 0.

| Index    | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 |
|----------|---|---|---|---|---|---|---|---|---|
| Elemento | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |

Es posible operar directamente con los elementos.

In [33]:
arr[0] + arr[5]

7

En el caso de las matrices, al indexar una posición se regresa el array de dicha posición.

In [34]:
matriz[0]

array([1, 2, 3])

| Index | 0 | 1 | 2 |
|-------|---|---|---|
| 0     | 1 | 2 | 3 |
| 1     | 4 | 5 | 6 |
| 2     | 7 | 8 | 9 |

Para seleccionar un solo elemento de la matriz se especifica la posición del elemento separada por comas.

Donde el primer elemento selecciona las filas, el segundo elemento las columnas

In [35]:
matriz[0][2]

3

### Slicing

Nos permite extraer varios datos, tiene un comienzo y un final.

In [36]:
arr[2:6]

array([3, 4, 5, 6])

Si no agregamos el **primer indice**, se tomara como inicio el 0

In [37]:
arr[:4]

array([1, 2, 3, 4])

Si no agregamos el **segundo indice**, se tomara como final el ultimo elemento

In [38]:
arr[5:]

array([6, 7, 8, 9])

Podemos utilizar un tercer indice, para poder indicar **los pasos**

Para recorrer todo el array de dos en dos

In [39]:
arr[::2]

array([1, 3, 5, 7, 9])

*Podemos también recorrer los elementos de derecha a izquierda utilizando indices negativos*

In [40]:
arr[-5:-2]

array([5, 6, 7])

De manera muy similar podemos trabajar con matrices

In [41]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

Para trabajar con filas y columnas especificas

In [42]:
matriz[1:,:2]

array([[4, 5],
       [7, 8]])

## Tipos de datos
Los arrays de NumPy solo pueden contener un tipo de dato, ya que esto es lo que le confiere las ventajas de la *optimización de memoria*.

### `.dtype`
Si necesitamos saber el tipo de datos del array utilizamos `.dtype`

In [43]:
arr.dtype

dtype('int32')

Podemos definir el tipo de datos desde la creación del array

In [44]:
arr = np.array([1, 2, 3, 4], dtype = 'float64')
arr.dtype

dtype('float64')

In [45]:
arr

array([1., 2., 3., 4.])

### `.astype`
Si ya tenemos definido el array y queremos cambiar su tipo lo podemos hacer con `.astype`

In [46]:
arr = arr.astype(np.int64)
arr

array([1, 2, 3, 4], dtype=int64)

Podemos utilizar esta sintaxis para otro tipo de datos

#### Booleano
*Al convertir a booleano todos los elementos distintos de 0 serán **True***

In [47]:
arr = np.array([0, 1, 2, 3, 4])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

#### String

Podemos llevar de *int* a *string*

In [48]:
arr = np.array([0, 1, 2, 3, 4])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S11')

Podemos realizar también el proceso inverso

In [49]:
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)

> *Debemos considerar que si intentamos convertir un string que contiene distintos tipos de datos obtendremos un error*

In [50]:
arr = np.array(['hola', '1', '2', '3', '4'])
arr = arr.astype(np.int8)
arr

ValueError: invalid literal for int() with base 10: 'hola'

## Dimensiones

Cuando trabajamos con datos es común encontrarlos agrupados de formas distintas, podemos entonces describir estos acomodos como dimensiones, permitiéndonos asi nombrarlos de la siguiente forma:

Escalar: \
Dim = 0 \
Un solo dato o valor
| 1 |
|---|

Vector: \
Dim = 1 \
Listas de Python (Elementos colocados en una fila)
| 0 | 1 | 2 | 3 | 4 |
|---|---|---|---|---|

Matriz: \
Dim = 2 \
Hojas de cálculo (Elementos agrupados en forma de filas y columnas)
| Color    | Pais     | Edad | Fruta   |
|----------|----------|------|---------|
| Rojo     | España   | 24   | Pera    |
| Amarillo | Colombia | 30   | Manzana |

Tensor: \
Dim >= 3 \
Series de tiempo o imágenes (Objetos agrupados por capas)

### `.ndim`

Si fuese necesario conocer la dimension de un objeto, podemos conocerla utilizando `.ndim`

#### Declarando un escalar

In [51]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

#### Declarando un vector

In [52]:
vector = np.array([1, 2, 3, 4])
print(vector)
vector.ndim

[1 2 3 4]


1

#### Declarando una matriz

In [53]:
Matriz = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

#### Declarando un tensor

In [54]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],[[13, 13, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 13 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]


3

El parámetro `.ndim`, nos permite declarar directamente el array con el numero de dimensiones

In [55]:
vector = np.array([1, 2, 3], ndmin = 10)
print(vector) 
vector.ndim 

[[[[[[[[[[1 2 3]]]]]]]]]]


10

### `expand_dims()`

También podemos expandir las dimensiones de nuestro array con el método `expand_dims()`, donde utilizaremos **axis** = 0 que hace referencia a las filas y/o **axis** = 1 que hace referencia a las columnas.

In [56]:
expand = np.expand_dims(np.array([1, 2, 3]), axis = 0)
print(expand)
expand.ndim 

[[1 2 3]]


2

### `squeeze`

Utilizaremos `squeeze` si lo que buscamos es remover(comprimir) las dimensiones que no están siendo ocupadas

In [57]:
print(vector, vector.ndim) 
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
