# NumPy

###### **Indice**
* [NumPy](#numpy)
  * [Array](#array)
    * [Slicing](#slicing)

Si queremos hacer uso de la librería es necesario importarla, la forma mas común de hacerlo es la siguiente:

In [1]:
import numpy as np

## Array
El array es el principal objeto de la librería. Representa datos de manera estructurada y se puede acceder a ellos a través del indexado, a un dato específico o un grupo de muchos datos específicos.

In [2]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

Convertimos nuestra lista en un array

In [3]:
arr = np.array(lista)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Una matriz son varios Vectores o listas agrupadas una encima de la otra

In [4]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

El indexado nos permite acceder a los elementos de los array y matrices
Los elementos se empiezan a contar desde 0.

| Index    | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 |
|----------|---|---|---|---|---|---|---|---|---|
| Elemento | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |

Es posible operar directamente con los elementos.

In [5]:
arr[0] + arr[5]

7

En el caso de las matrices, al indexar una posición se regresa el array de dicha posición.

In [6]:
matriz[0]

array([1, 2, 3])

| Index | 0 | 1 | 2 |
|-------|---|---|---|
| 0     | 1 | 2 | 3 |
| 1     | 4 | 5 | 6 |
| 2     | 7 | 8 | 9 |

Para seleccionar un solo elemento de la matriz se especifica la posición del elemento separada por comas.

Donde el primer elemento selecciona las filas, el segundo elemento las columnas

In [7]:
matriz[0][2]

3

### Slicing

Nos permite extraer varios datos, tiene un comienzo y un final.

In [8]:
arr[2:6]

array([3, 4, 5, 6])

Si no agregamos el **primer indice**, se tomara como inicio el 0

In [9]:
arr[:4]

array([1, 2, 3, 4])

Si no agregamos el **segundo indice**, se tomara como final el ultimo elemento

In [10]:
arr[5:]

array([6, 7, 8, 9])

Podemos utilizar un tercer indice, para poder indicar **los pasos**

Para recorrer todo el array de dos en dos

In [11]:
arr[::2]

array([1, 3, 5, 7, 9])

*Podemos también recorrer los elementos de derecha a izquierda utilizando indices negativos*

In [12]:
arr[-5:-2]

array([5, 6, 7])

De manera muy similar podemos trabajar con matrices

In [13]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

Para trabajar con filas y columnas especificas

In [14]:
matriz[1:,:2]

array([[4, 5],
       [7, 8]])