# NumPy

###### **Indice**
* [NumPy](#numpy)
  * [Array](#array)
    * [Slicing](#slicing)
  * [Tipos de datos](#tipos-de-datos)
    * [`.dtype`](#.dtype)
    * [`.astype`](#.astype)

Si queremos hacer uso de la librería es necesario importarla, la forma mas común de hacerlo es la siguiente:

In [1]:
import numpy as np

## Array
El array es el principal objeto de la librería. Representa datos de manera estructurada y se puede acceder a ellos a través del indexado, a un dato específico o un grupo de muchos datos específicos.

In [2]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

Convertimos nuestra lista en un array

In [3]:
arr = np.array(lista)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Una matriz son varios Vectores o listas agrupadas una encima de la otra

In [4]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

El indexado nos permite acceder a los elementos de los array y matrices
Los elementos se empiezan a contar desde 0.

| Index    | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 |
|----------|---|---|---|---|---|---|---|---|---|
| Elemento | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |

Es posible operar directamente con los elementos.

In [5]:
arr[0] + arr[5]

7

En el caso de las matrices, al indexar una posición se regresa el array de dicha posición.

In [6]:
matriz[0]

array([1, 2, 3])

| Index | 0 | 1 | 2 |
|-------|---|---|---|
| 0     | 1 | 2 | 3 |
| 1     | 4 | 5 | 6 |
| 2     | 7 | 8 | 9 |

Para seleccionar un solo elemento de la matriz se especifica la posición del elemento separada por comas.

Donde el primer elemento selecciona las filas, el segundo elemento las columnas

In [7]:
matriz[0][2]

3

### Slicing

Nos permite extraer varios datos, tiene un comienzo y un final.

In [8]:
arr[2:6]

array([3, 4, 5, 6])

Si no agregamos el **primer indice**, se tomara como inicio el 0

In [9]:
arr[:4]

array([1, 2, 3, 4])

Si no agregamos el **segundo indice**, se tomara como final el ultimo elemento

In [10]:
arr[5:]

array([6, 7, 8, 9])

Podemos utilizar un tercer indice, para poder indicar **los pasos**

Para recorrer todo el array de dos en dos

In [11]:
arr[::2]

array([1, 3, 5, 7, 9])

*Podemos también recorrer los elementos de derecha a izquierda utilizando indices negativos*

In [12]:
arr[-5:-2]

array([5, 6, 7])

De manera muy similar podemos trabajar con matrices

In [13]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

Para trabajar con filas y columnas especificas

In [14]:
matriz[1:,:2]

array([[4, 5],
       [7, 8]])

## Tipos de datos
Los arrays de NumPy solo pueden contener un tipo de dato, ya que esto es lo que le confiere las ventajas de la *optimización de memoria*.

### `.dtype`
Si necesitamos saber el tipo de datos del array utilizamos `.dtype`

In [15]:
arr.dtype

dtype('int32')

Podemos definir el tipo de datos desde la creación del array

In [19]:
arr = np.array([1, 2, 3, 4], dtype = 'float64')
arr.dtype

dtype('float64')

In [20]:
arr

array([1., 2., 3., 4.])

### `.astype`
Si ya tenemos definido el array y queremos cambiar su tipo lo podemos hacer con `.astype`

In [23]:
arr = arr.astype(np.int64)
arr

array([1, 2, 3, 4], dtype=int64)

Podemos utilizar esta sintaxis para otro tipo de datos

#### Booleano
*Al convertir a booleano todos los elementos distintos de 0 serán **True***

In [24]:
arr = np.array([0, 1, 2, 3, 4])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

#### String

Podemos llevar de *int* a *string*

In [25]:
arr = np.array([0, 1, 2, 3, 4])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S11')

Podemos realizar también el proceso inverso

In [27]:
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)

> *Debemos considerar que si intentamos convertir un string que contiene distintos tipos de datos obtendremos un error*

In [28]:
arr = np.array(['hola', '1', '2', '3', '4'])
arr = arr.astype(np.int8)
arr

ValueError: invalid literal for int() with base 10: 'hola'