# NumPy

###### **Indice**
* [NumPy](#numpy)
  * [Array](#array)
    * [Slicing](#slicing)
  * [Tipos de datos](#tipos-de-datos)
    * [`.dtype`](#.dtype)
    * [`.astype`](#.astype)
  * [Dimensiones](#dimensiones)
    * [`.ndim`](#.ndim)
    * [`expand_dims()`](#expand_dims)
    * [`squeeze`](#squeeze)
  * [Creando arrays](#creando-arrays)
    * [`arange()`](#arange)
    * [`zeros()`](#zeros)
    * [`ones()`](#ones)
    * [`linspace()`](#linspace)
    * [`eye()`](#eye)
    * [`random.rand()`](#randomrand)
    * [`random.randint()`](#randomrandint)
  * [Shape y reshape](#shape-y-reshape)
    * [`shape`](#shape)
    * [`reshape`](#reshape)
  * [Funciones principales](#funciones-principales)
    * [`max()`](#max)
    * [`min()`](#min)
    * [`ptp()`](#ptp)
    * [Análisis estadístico](#análisis-estadístico)
    * [`concatenate()`](#concatenate)

Si queremos hacer uso de la librería es necesario importarla, la forma mas común de hacerlo es la siguiente:

In [1]:
import numpy as np

## Array
El array es el principal objeto de la librería. Representa datos de manera estructurada y se puede acceder a ellos a través del indexado, a un dato específico o un grupo de muchos datos específicos.

In [2]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

Convertimos nuestra lista en un array

In [3]:
arr = np.array(lista)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Una matriz son varios Vectores o listas agrupadas una encima de la otra

In [4]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

El indexado nos permite acceder a los elementos de los array y matrices
Los elementos se empiezan a contar desde 0.

| Index    | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 |
|----------|---|---|---|---|---|---|---|---|---|
| Elemento | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |

Es posible operar directamente con los elementos.

In [5]:
arr[0] + arr[5]

7

En el caso de las matrices, al indexar una posición se regresa el array de dicha posición.

In [6]:
matriz[0]

array([1, 2, 3])

| Index | 0 | 1 | 2 |
|-------|---|---|---|
| 0     | 1 | 2 | 3 |
| 1     | 4 | 5 | 6 |
| 2     | 7 | 8 | 9 |

Para seleccionar un solo elemento de la matriz se especifica la posición del elemento separada por comas.

Donde el primer elemento selecciona las filas, el segundo elemento las columnas

In [7]:
matriz[0][2]

3

### Slicing

Nos permite extraer varios datos, tiene un comienzo y un final.

In [8]:
arr[2:6]

array([3, 4, 5, 6])

Si no agregamos el **primer indice**, se tomara como inicio el 0

In [9]:
arr[:4]

array([1, 2, 3, 4])

Si no agregamos el **segundo indice**, se tomara como final el ultimo elemento

In [10]:
arr[5:]

array([6, 7, 8, 9])

Podemos utilizar un tercer indice, para poder indicar **los pasos**

Para recorrer todo el array de dos en dos

In [11]:
arr[::2]

array([1, 3, 5, 7, 9])

*Podemos también recorrer los elementos de derecha a izquierda utilizando indices negativos*

In [12]:
arr[-5:-2]

array([5, 6, 7])

De manera muy similar podemos trabajar con matrices

In [13]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

Para trabajar con filas y columnas especificas

In [14]:
matriz[1:,:2]

array([[4, 5],
       [7, 8]])

## Tipos de datos
Los arrays de NumPy solo pueden contener un tipo de dato, ya que esto es lo que le confiere las ventajas de la *optimización de memoria*.

### `.dtype`
Si necesitamos saber el tipo de datos del array utilizamos `.dtype`

In [15]:
arr.dtype

dtype('int32')

Podemos definir el tipo de datos desde la creación del array

In [16]:
arr = np.array([1, 2, 3, 4], dtype = 'float64')
arr.dtype

dtype('float64')

In [17]:
arr

array([1., 2., 3., 4.])

### `.astype`
Si ya tenemos definido el array y queremos cambiar su tipo lo podemos hacer con `.astype`

In [18]:
arr = arr.astype(np.int64)
arr

array([1, 2, 3, 4], dtype=int64)

Podemos utilizar esta sintaxis para otro tipo de datos

#### Booleano
*Al convertir a booleano todos los elementos distintos de 0 serán **True***

In [19]:
arr = np.array([0, 1, 2, 3, 4])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

#### String

Podemos llevar de *int* a *string*

In [20]:
arr = np.array([0, 1, 2, 3, 4])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S11')

Podemos realizar también el proceso inverso

In [21]:
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)

> *Debemos considerar que si intentamos convertir un string que contiene distintos tipos de datos obtendremos un error*

In [22]:
arr = np.array(['hola', '1', '2', '3', '4'])
arr = arr.astype(np.int8)
arr

ValueError: invalid literal for int() with base 10: 'hola'

## Dimensiones

Cuando trabajamos con datos es común encontrarlos agrupados de formas distintas, podemos entonces describir estos acomodos como dimensiones, permitiéndonos asi nombrarlos de la siguiente forma:

Escalar: \
Dim = 0 \
Un solo dato o valor

| 1 |
|---|

Vector: \
Dim = 1 \
Listas de Python (Elementos colocados en una fila)

| 0 | 1 | 2 | 3 | 4 |
|---|---|---|---|---|

Matriz: \
Dim = 2 \
Hojas de cálculo (Elementos agrupados en forma de filas y columnas)

| Color    | País     | Edad | Fruta   |
|----------|----------|------|---------|
| Rojo     | España   | 24   | Pera    |
| Amarillo | Colombia | 30   | Manzana |

Tensor: \
Dim >= 3 \
Series de tiempo o imágenes (Objetos agrupados por capas)

### `.ndim`

Si fuese necesario conocer la dimension de un objeto, podemos conocerla utilizando `.ndim`

#### Declarando un escalar

In [23]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

#### Declarando un vector

In [24]:
vector = np.array([1, 2, 3, 4])
print(vector)
vector.ndim

[1 2 3 4]


1

#### Declarando una matriz

In [25]:
Matriz = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

#### Declarando un tensor

In [26]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],[[13, 13, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 13 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]


3

El parámetro `.ndim`, nos permite declarar directamente el array con el numero de dimensiones

In [27]:
vector = np.array([1, 2, 3], ndmin = 10)
print(vector) 
vector.ndim 

[[[[[[[[[[1 2 3]]]]]]]]]]


10

### `expand_dims()`

También podemos expandir las dimensiones de nuestro array con el método `expand_dims()`, donde utilizaremos **axis** = 0 que hace referencia a las filas y/o **axis** = 1 que hace referencia a las columnas.

In [28]:
expand = np.expand_dims(np.array([1, 2, 3]), axis = 0)
print(expand)
expand.ndim 

[[1 2 3]]


2

### `squeeze`

Utilizaremos `squeeze` si lo que buscamos es remover(comprimir) las dimensiones que no están siendo ocupadas

In [29]:
print(vector, vector.ndim) 
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


## Creando arrays

NumPy nos brinda la posibilidad de crear arrays completamente desde 0, lo cual facilita el trabajo al no necesitar realizar una declaración antes


### `arange()`

Nos permite crear arrays desde un elemento inicial hasta uno final (similar al `range()` nativo de Python)

In [30]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Si queremos definir pasos en especifico, bastara simplemente con agregar una tercer entrada

In [31]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

### `zeros()` 

Nos permite definir estructuras o esquemas compuestas en su totalidad por ceros

In [32]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [33]:
np.zeros((10, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### `ones()`

Nos permite definir estructuras o esquemas compuestas en su totalidad por unos

In [34]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [35]:
np.ones((10, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### `linspace()` 

Permite generar una array definiendo un inicio, un final y cuantas divisiones tendrá, esto creando divisiones exactamente iguales para cubrir el tamaño total

In [36]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

### `eye()`

Nos permite generar una matriz identidad (solo tiene unos en su diagonal principal el resto son ceros)

In [37]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### `random.rand()`

Nos permite generar números aleatorios entre 0 y 1

Un solo elemento aleatorio

In [38]:
np.random.rand()

0.2965571772546597

Un array de números aleatorios

In [39]:
np.random.rand(4)

array([0.15922258, 0.41850573, 0.17946317, 0.47418004])

Una matriz de números aleatorios

In [40]:
np.random.rand(4, 4)

array([[0.73767427, 0.20128123, 0.34824232, 0.95529103],
       [0.45692098, 0.19396337, 0.13788077, 0.03433797],
       [0.81310775, 0.38401704, 0.45448291, 0.36498674],
       [0.89364346, 0.96678096, 0.18808039, 0.50792595]])

### `random.randint()`

Nos permite generar números aleatorios enteros entre dos valores específicos

Solo genera un elemento

In [41]:
np.random.randint(1, 15)

13

Generando los elementos necesarios para rellenar una estructura definida

In [42]:
np.random.randint(1, 15, (3, 3))

array([[ 9,  4,  4],
       [14,  3, 11],
       [ 3,  7,  9]])

## Shape y Reshape

La forma de un arreglo nos va a decir con que estructura se está trabajando (tamaño, manipular, ingresar)

### `Shape`

Nos indica la forma del arreglo

In [43]:
arr = np.random.randint(1, 10, (3, 2))
arr.shape

(3, 2)

### `reshape`

Transforma el arreglo, siempre y cuando se mantenga el numero de elementos del arreglo original

In [44]:
arr

array([[8, 4],
       [6, 1],
       [9, 6]])

In [45]:
arr.reshape(1, 6)

array([[8, 4, 6, 1, 9, 6]])

Podemos hacer reshape como lo haría **C**

In [46]:
np.reshape(arr, (2, 3), 'C')

array([[8, 4, 6],
       [1, 9, 6]])

Podemos hacer reshape como lo haría **Fortran**

In [47]:
np.reshape(arr, (2, 3), 'F')

array([[8, 9, 1],
       [6, 4, 6]])

Podemos también hacer reshape según la **optimización de nuestro equipo**

In [48]:
np.reshape(arr, (2, 3), 'A')

array([[8, 4, 6],
       [1, 9, 6]])

## Funciones principales

### `max()`

Nos permite localizar el numero mayor que se encuentra en nuestro objeto

In [66]:
matriz = np.random.randint(0, 10, (3,3))
matriz

array([[0, 8, 6],
       [7, 1, 0],
       [9, 5, 9]])

In [50]:
matriz.max()

9

Si lo que buscamos es el máximo de cada fila o columna lo podemos obtener especificando el eje

| 0 | Columnas |
|---|----------|
| 1 | Filas    |

In [51]:
matriz.max(0)

array([7, 8, 9])

In [52]:
matriz.max(1)

array([3, 6, 9])

#### `argmax()`

Nos muestra la posición del máximo en nuestro objeto

In [54]:
arr.argmax()

4

En el caso de una matriz obtendremos un array con la posición donde se encuentra el máximo de una fila o columna

In [67]:
matriz.argmax(0)

array([2, 0, 2], dtype=int64)

In [68]:
matriz.argmax(1)

array([1, 0, 0], dtype=int64)

### `min()`

Funciona de la misma manera que `max()`, pero mostrando el elemento menor

In [69]:
matriz.min()

0

In [70]:
matriz.min(0)

array([0, 1, 0])

#### `argmin()`

Funciona igual que `argmax()` pero con el valor mínimo

In [71]:
matriz.argmin(0)

array([0, 1, 1], dtype=int64)

### `ptp()`

Nos permite calcular la distancia entre máximo y mínimo

In [72]:
arr.ptp()

8

In [73]:
matriz.ptp(0)

array([9, 7, 9])

### Análisis estadístico

También tenemos algunas funciones que nos permiten realizar acciones especificas como:

#### `sort()`

Ordenar elementos

In [79]:
arr = np.random.randint(1, 20, 10)
arr

array([19, 10,  9,  9, 15, 13,  3,  5,  9, 13])

In [81]:
arr.sort()
arr

array([ 3,  5,  9,  9,  9, 10, 13, 13, 15, 19])

#### `percentile()`

Obtener un percentile

In [83]:
np.percentile(arr, 50)

9.5

#### `median()`

In [84]:
np.median(arr)

9.5

#### `std()`

Obtenemos la desviación estándar

In [85]:
np.std(arr)

4.455333881989093

#### `var()`

Obtenemos la varianza

In [86]:
np.var(arr)

19.85

#### `mean()`

Obtenemos el promedio

In [87]:
np.mean(arr)

10.5

> Estas funciones pueden ser aplicadas también a matrices

### `concatenate()`

Podemos concatenar elementos

In [88]:
a = np.array([[1,2], [3,4]])
b = np.array([5, 6])

Para poder concatenar elementos es necesario que ambos tengan la misma dimension

In [89]:
b = np.expand_dims(b, axis = 0)
np.concatenate((a, b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

Si quisiéramos concatenar el otro eje Como ‘b’ es una fila y no una columna, no se puede concatenar a menos que se aplique la transpuesta.

In [90]:
np.concatenate((a, b), axis = 1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [91]:
b.T

array([[5],
       [6]])

In [92]:
np.concatenate((a, b.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])